version: '3.9'

services:
  db:
    container_name: postgres
    image:
      postgres:16.1-alpine3.19
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${PG_USER-imagocms}
      - POSTGRES_PASSWORD=${PG_PSWD-imagocms_pass}

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    links:
      - db:db
    environment:
      - SECRET_KEY=${SECRET-dev}
      - POSTGRES_HOST=${DB_HOST-db}
      - POSTGRES_USER=${PG_USER-imagocms}
      - POSTGRES_PASSWORD=${PG_PSWD-imagocms_pass}
    ports:
      - "5050:5050"
    volumes:
      - app-data:/app/imagocms/static/images

volumes:
  db-data:
  app-data:
